#include<stdio.h>
int main()
{
    int i,p,j;
    char str[150],str1[30]="qwertyuiop",str2[30]="asdfghjkl;",str3[30]="zxcvbnm,./",ch;
    scanf("%c",&ch);
    scanf("%s",str);
    if(ch=='R')
    {
        for(i=0;str[i]!='\0';i++)
        {
            p=0;
            for(j=0;str1[j]!='\0';j++)
            {
                if(str[i]==str1[j])
                {
                  printf("%c",str1[j-1]);
                  p=1;
                }
            }
            if(p==0)
            {
                for(j=0;str2[j]!='\0';j++)
            {
                if(str[i]==str2[j])
                {
                  printf("%c",str2[j-1]);
                  p=1;
                }
            }
            }
            if(p==0)
            {
                for(j=0;str3[j]!='\0';j++)
            {
                if(str[i]==str3[j])
                {
                  printf("%c",str3[j-1]);
                  p=1;
                }
            }
            }
        }
    }
    else
    {
        for(i=0;str[i]!='\0';i++)
        {
            p=0;
            for(j=0;str1[j]!='\0';j++)
            {
                if(str[i]==str1[j])
                {
                  printf("%c",str1[j+1]);
                  p=1;
                }
            }
            if(p==0)
            {
                for(j=0;str2[j]!='\0';j++)
            {
                if(str[i]==str2[j])
                {
                  printf("%c",str2[j+1]);
                  p=1;
                }
            }
            }
            if(p==0)
            {
                for(j=0;str3[j]!='\0';j++)
            {
                if(str[i]==str3[j])
                {
                  printf("%c",str3[j+1]);
                  p=1;
                }
            }
            }
        }
    }
}
